### ISSUE TITLE
Firmware Update nicht möglich - Bad Request

### ISSUE THREAD

**Issue by iroc-fabi** [markusdd/OpenDTUFusionDocs#11]
Ich wollte die Firmware von dieser Seite installieren:
[openDTU Skippermeister](https://github.com/skippermeister/OpenDTU-OnBattery/releases/tag/2024.07.01-2)
Leider bekomme ich immer die Meldung OTA-Fehler Bad Request.
Hat das etwas mit den Partitionen zu tun?
Wie kann man sie ggf. anpassen?

**Comment by markusdd** [comment]
Hallo, ich weiß nicht  ob das Problem mittlerweile gelst ist, ich habe für dieses issue leider von Github nie eine notification erhalten.

Generell ist OpenDTUonBattery aber ein separates Community Projekt und ein OTA kann nciht direkt auf OpenDTU aufgespielt werden. Dazu muss das Gerät neu geflasht werden. Support und Soku dazu gibt es bei OpenDTUonBattery heir auf Github oder auf dem discord server.
