### ISSUE TITLE
Question: Does the  CAN/Iso extension shield fit into the AllianceApps Box?

### ISSUE THREAD

**Issue by Manos1966** [markusdd/OpenDTUFusionDocs#15]
Sorry Markus, I did not know where to raise the question:

I see at the AllianceApps website, a Boxed version of the Fusion is offered:
https://shop.allianceapps.io/products/allianceapps-opendtu-fusion?pr_prod_strat=e5_desc&pr_rec_id=cc17aa39f

- Can I order this version (because "Laziness" is my middle name), open the box and add the CAN/Iso extension shield into it?
- Is there an elegant solution to get the CANbus RJ45 cable out of the AllianceApps box? (looking for ideas)

Best regards
Manos

**Comment by markusdd** [comment]
The base Fusion DTU case is NOT built to support any of the Shields.

There is a community-made case though with support for the PoE shield that probably would be better suited: https://www.thingiverse.com/thing:6371201

Here you could use the hole for the RJ45 Jack to feed the cables inside.

**Comment by Sorbat** [comment]
@Manos1966 vielleicht wäre das sonst eine alternative? https://3printd-solution.eu/Fusion-2x-Gehaeuse-Konfigurator-Extrudr-NX2-MATT-BLACK-RAL-9017-Fusion-Board-mit-PoE

**Comment by Manos1966** [comment]
Danke @Sorbat 👍

**Comment by markusdd** [comment]
I think this has been answered :D
