### ISSUE TITLE
Radio modules not recognized after OTA update

### ISSUE THREAD

**Issue by 0per8or** [markusdd/OpenDTUFusionDocs#2]
I recently bought a OpenDTU Fusion board. After trying to do a OTA update to the latest version it seems that the radio modules do not get recognized correctly.

![2023-07-05 08_01_34-OpenDTU](https://github.com/markusdd/OpenDTUFusionDocs/assets/31338564/2935e1b8-e5fb-401e-8d0e-2098f98b6b53)
![2023-07-05 08_01_53-OpenDTU](https://github.com/markusdd/OpenDTUFusionDocs/assets/31338564/94f475e3-ba6d-41bd-a61f-b08245834ab8)

**Comment by markusdd** [comment]
Hi. This can happen as the boards are delivered with a firmware that has the pins baked in.
If you update with the generic image you might need to load the opendtufusion specific device profile jason which has all the pin mapping options (also for displays) as described here: https://github.com/markusdd/OpenDTUFusionDocs/blob/main/FLASHED_START.md#loading-a-device-profile-for-the-rf-and-display-pinout

If you keep using the generic OTA builds in the future you should not need to do this again.

**Comment by 0per8or** [comment]
This fixed it for me. Thank you!

Maybe it is a good idea to put this kind of information to the Readme to prevent others from running into the same issue.

**Comment by markusdd** [comment]
Done: https://github.com/markusdd/OpenDTUFusionDocs/blob/main/OTA.md#attention-for-pre-flashed-boards
