### ISSUE TITLE
Example Configuration for CAN/Iso error

### ISSUE THREAD

**Issue by Mogdar-M** [markusdd/OpenDTUFusionDocs#20]
the Example JSON for the CAN/Iso has a error in it

 "victron": {
            "rx": 10,
            "tx": 9,
            "rx2": 11,
            "tx2": 12,
        }
    }
]

The comma after tx2:12 is wrong, the DTU is not accepting these file

**Comment by markusdd** [comment]
closing, thx for find and fix!
