### ISSUE TITLE
Size of Antennas

### ISSUE THREAD

**Issue by swingstate** [markusdd/OpenDTUFusionDocs#6]
Markus, 

can you share the size of the antennas? I am developing a case and want to ensure I plan for the space of the 3 foil antennas. 

Thanks!

**Comment by markusdd** [comment]
oh sorry, somehow I completely missed this ticket.

Are you sorted by now? Because I do not have one handy right now, I would ask Tim to runs the shop to measure them.

**Comment by Sorbat** [comment]
Is there any reason why we speak in English?

Die Folienantennen die bei mir dabei waren sind 40x15mm, ca. 0,25mm dick.
