### ISSUE TITLE
Canadian buyer try to buy

### ISSUE THREAD

**Issue by bebrouss** [markusdd/OpenDTUFusionDocs#9]

**Comment by d-allin** [comment]
Fellow canuck here. Not really sure if asking this in the bug report section of their documentation repository is kosher, but I'll chime in.
After much faffing about on their online store (which says they ship to Canada, but then won't let you go through checkout), I ended up buying one from their ebay store (https://www.ebay.ca/usr/allianceapps).
Arrived in a week or so. No issues.

**Comment by markusdd** [comment]
Hi guys, I'm indeed not running the sales operations. But @cat24max does. Tim, is it known that outside EU sales are not possible in the allianceapps store?
